window.productsData = [
  // Educational
  { name: "Humanoid G1 (Base/EDU)", image: "assets/products_shop_images/Humanoid_G1__BaseEDU__1.png", category: "Educational", url: "humanoid-g1-base-edu.html" },
  { name: "Humanoid Mini Hi", image: "assets/products_shop_images/Humanoid_Mini_Hi_1.png", category: "Educational", url: "humanoid-mini-hi.html" },
  { name: "Mini pi Bipedal Robot", image: "assets/products_shop_images/Mini_p_Bipedal_Robot_1.png", category: "Educational", url: "mini-pi-bipedal-robot.html" },
  { name: "Robodog Go1", image: "assets/products_shop_images/Robodog_Go1_1.png", category: "Educational", url: "robodog-go1.html" },

  // Specialty
  { name: "Humanoid H1", image: "assets/products_shop_images/Humanoid_H1_1.png", category: "Specialty", url: "humanoid-h1.html" },
  { name: "Humanoid Oli", image: "assets/products_shop_images/Humanoid_Oli_1.png", category: "Specialty", url: "humanoid-oli.html" },
  { name: "Humanoid R1", image: "assets/products_shop_images/Humanoid_R1.png", category: "Specialty", url: "humanoid-r1.html" },
  { name: "Robodog B2", image: "assets/products_shop_images/Robodog_B2.png", category: "Specialty", url: "robodog-b2.html" },
  { name: "Robodog (B2/B2-W)", image: "assets/products_shop_images/Robodog__B2B2-W__1.png", category: "Specialty", url: "robodog-b2-b2-w.html" },
  { name: "Robodog (Go2/Go2-W)", image: "assets/products_shop_images/Robodog__Go2Go2-W__1.png", category: "Specialty", url: "robodog-go2-go2-w.html" },
  { name: "Tron 1", image: "assets/products_shop_images/Tron_1_1.png", category: "Specialty", url: "tron-1.html" },

  // Nimble Drones
  { name: "Nimble Base Kit", image: "assets/products_shop_images/flapper-nimble-base-kit_1.png", category: "Nimble Drones", url: "nimble-base-kit.html" },
  { name: "Nimble Starter Kit", image: "assets/products_shop_images/flapper-nimble-starter-kit_1.png", category: "Nimble Drones", url: "nimble-starter-kit.html" },
  { name: "Nimble Lighthouse Bundle", image: "assets/products_shop_images/flapper-nimble-lighthouse-bundle_1.png", category: "Nimble Drones", url: "nimble-lighthouse-bundle.html" },
  { name: "Base Multi Kit (2x)", image: "assets/products_shop_images/base-multi-kit-2x_1.png", category: "Nimble Drones", url: "base-multi-kit-2x.html" },
  { name: "Base Multi Kit (3x)", image: "assets/products_shop_images/base-multi-kit-3x_1.png", category: "Nimble Drones", url: "base-multi-kit-3x.html" },
  { name: "Nimble Swarm Bundle (x4)", image: "assets/products_shop_images/flapper-nimble-swarm-bundlex4_1.png", category: "Nimble Drones", url: "nimble-swarm-bundle-x4.html" },

  // Service
  { name: "Delivery Robot (closed type)", image: "assets/products_shop_images/Delivery_Robot__closed_type__1.png", category: "Service", url: "delivery-robot-closed-type.html" },
  { name: "Disinfectant Mini Robot", image: "assets/products_shop_images/Disinfectant_Mini_Robot_1.png", category: "Service", url: "disinfectant-mini-robot.html" },
  { name: "Factory Delivery Robot", image: "assets/products_shop_images/Factory_Delivery_Robot_1.png", category: "Service", url: "factory-delivery-robot.html" },
  { name: "Healthcare Robot", image: "assets/products_shop_images/Healthcare_Robot.png", category: "Service", url: "healthcare-robot.html" },
  { name: "Hotel Robot", image: "assets/products_shop_images/Hotel_Robot_1.png", category: "Service", url: "hotel-robot.html" },
  { name: "Mars Smartbot", image: "assets/products_shop_images/Mars_Smartbot_1.png", category: "Service", url: "mars-smartbot.html" },
  { name: "Water 2", image: "assets/products_shop_images/Water 2_1.png", category: "Service", url: "water-2.html" },

  // Industrial
  { name: "Base Chassis", image: "assets/products_shop_images/Base_Chassis_1.png", category: "Industrial", url: "base-chassis.html" },
  { name: "Dual Arm Compound Robot", image: "assets/products_shop_images/Dual_Arm_Compound_Robot.png", category: "Industrial", url: "dual-arm-compound-robot.html" },
  { name: "Heavy Load AMR", image: "assets/products_shop_images/Heavy_Load_AMR_1.png", category: "Industrial", url: "heavy-load-amr.html" },
  { name: "L Lift AMR", image: "assets/products_shop_images/Factory_Delivery_Robot_1.png", category: "Industrial", url: "l-lift-amr.html" },
  { name: "Smart Forklift", image: "assets/products_shop_images/Smart_Forklift.png", category: "Industrial", url: "smart-forklift.html" },
  { name: "Sub Lift Robot", image: "assets/products_shop_images/Sub_Lift_Robot_1.png", category: "Industrial", url: "sub-lift-robot.html" },
  { name: "Hermes Chassis", image: "assets/products_shop_images/Hermes Chassis_1.png", category: "Industrial", url: "hermes-chassis.html" },
  { name: "Robodog AlienGo", image: "assets/products_shop_images/Robodog_AlienGo_1.png", category: "Industrial", url: "robodog-aliengo.html" },
  { name: "Robotic Arm (ECO62-B)", image: "assets/products_shop_images/Robotic_Arm__ECO62-B.png", category: "Industrial", url: "robotic-arm-eco62-b.html" },
  { name: "Robotic Arm (ECO65-6F)", image: "assets/products_shop_images/Robotic_Arm__ECO65-6F.png", category: "Industrial", url: "robotic-arm-eco65-6f.html" },
  { name: "Robotic Arm (ECO65-B)", image: "assets/products_shop_images/Robotic_Arm__ECO65-B.png", category: "Industrial", url: "robotic-arm-eco65-b.html" },
  { name: "Robotic Arm (GEN72-B)", image: "assets/products_shop_images/Robotic_Arm__GEN72-B.png", category: "Industrial", url: "robotic-arm-gen72-b.html" },
  { name: "Robotic Arm (RM65-6F)", image: "assets/products_shop_images/Robotic_Arm__RM65-6F.png", category: "Industrial", url: "robotic-arm-rm65-6f.html" },
  { name: "Robotic Arm (RM65-B)", image: "assets/products_shop_images/Robotic_Arm__RM65-B.png", category: "Industrial", url: "robotic-arm-rm65-b.html" },
  { name: "Robotic Arm (RM75-6F)", image: "assets/products_shop_images/Robotic_Arm__RM75-6F.png", category: "Industrial", url: "robotic-arm-rm75-6f.html" },
  { name: "Robotic Arm (RM75-B)", image: "assets/products_shop_images/Robotic_Arm__RM75-B.png", category: "Industrial", url: "robotic-arm-rm75-b.html" },
  { name: "Robotic Arm (RML63-6F)", image: "assets/products_shop_images/Robotic_Arm__RML63-6F.png", category: "Industrial", url: "robotic-arm-rml63-6f.html" },
  { name: "Robotic Arm (RML63-B)", image: "assets/products_shop_images/Robotic_Arm__RML63-B.png", category: "Industrial", url: "robotic-arm-rml63-b.html" },
  { name: "Single Arm Compound Robot - Precision, Mobility, and Versatility", image: "assets/products_shop_images/Single_Arm_Compound_Robot___Precision__Mobility__and_Versatility.png", category: "Industrial", url: "single-arm-compound-robot-precision-mobility-and-versatility.html" },
  { name: "Single Arm Lifting Compound Robot", image: "assets/products_shop_images/Single_Arm_Lifting_Compound_Robot_1.png", category: "Industrial", url: "single-arm-lifting-compound-robot.html" },
  { name: "Single Arm Compound Robot - Compact, Mobile, and Intelligent Automation", image: "assets/products_shop_images/Single_Arm_Compound_Robot___Compact__Mobile__and_Intelligent_Automation.png", category: "Industrial", url: "single-arm-compound-robot-compact-mobile-and-intelligent-automation.html" },

  // Accessories
  { name: "Camera (RM-MVQ)", image: "assets/products_shop_images/Camera_RM-MVQ__1.png", category: "Accessories", url: "camera-rm-mvq.html" },
  { name: "Camera (D435C)", image: "assets/products_shop_images/Camera__D435C.png", category: "Accessories", url: "camera-d435c.html" },
  { name: "Camera (DaBai DCW)", image: "assets/products_shop_images/Camera__DaBai_DCW.png", category: "Accessories", url: "camera-dabai-dcw.html" },
  { name: "Dex. Hand (RM56S2B) 2L/2R", image: "assets/products_shop_images/Dex._Hand__RM56S2B__2L2R_1.png", category: "Accessories", url: "dex-hand-rm56s2b-2l-2r.html" },
  { name: "Flexible Gripper (RM-SFG)", image: "assets/products_shop_images/Flexible_Gripper__RM-SFG.png", category: "Accessories", url: "flexible-gripper-rm-sfg.html" },
  { name: "Gripper (AG-160-95)", image: "assets/products_shop_images/Gripper__AG-160-95__1.png", category: "Accessories", url: "gripper-ag-160-95.html" },
  { name: "Gripper (EG2-SF16)", image: "assets/products_shop_images/Gripper__EG2-SF16__1.png", category: "Accessories", url: "gripper-eg2-sf16.html" },
  { name: "Gripper (ERG32-150)", image: "assets/products_shop_images/Gripper__ERG32-150.png", category: "Accessories", url: "gripper-erg32-150.html" },
  { name: "Gripper (EVS08)", image: "assets/products_shop_images/Gripper__EVS08_1.png", category: "Accessories", url: "gripper-evs08.html" },
  { name: "Gripper (RGS2-050)", image: "assets/products_shop_images/Gripper__RG52-050.png", category: "Accessories", url: "gripper-rgs2-050.html" },
  { name: "Gripper (RGI-100-30)", image: "assets/products_shop_images/Gripper__RGI-100-30.png", category: "Accessories", url: "gripper-rgi-100-30.html" },
  { name: "Crazyradio 2.0", image: "assets/products_shop_images/crazyradio-2-usb-dongle_1.png", category: "Accessories", url: "crazyradio-2-0.html" },
  { name: "Lighthouse Base Station", image: "assets/products_shop_images/lighthouse-base-station.png", category: "Accessories", url: "lighthouse-base-station.html" },
  { name: "Lighthouse Support Kit", image: "assets/products_shop_images/lighthouse-support-kit-for-nimble_1.png", category: "Accessories", url: "lighthouse-support-kit.html" },
  { name: "Nimble Battery", image: "assets/products_shop_images/battery-for-nimble.png", category: "Accessories", url: "nimble-battery.html" },
  { name: "Nimble Shells", image: "assets/products_shop_images/set-of-body-shells-for-nimble.png", category: "Accessories", url: "nimble-shells.html" },
  { name: "Wing Set", image: "assets/products_shop_images/butterfly-wing-set-for-nimble_1.png", category: "Accessories", url: "wing-set.html" },
  { name: "2.4 GHz Transmitter", image: "assets/products_shop_images/24-ghz-transmitter-with-edge-tx_1.png", category: "Accessories", url: "transmitter-2-4ghz.html" },
  { name: "FrSky Receiver", image: "assets/products_shop_images/frsky-receiver.png", category: "Accessories", url: "frsky-receiver.html" },
  { name: "Extension Cable for Nimble", image: "assets/products_shop_images/extension-cable-for-nimble.png", category: "Accessories", url: "contact-us.html" },
  { name: "Extra Wing Set (white)", image: "assets/products_shop_images/extra-wing-set-for-nimble_1.png", category: "Accessories", url: "contact-us.html" },
  { name: "Hex Key Tool (1.5 mm)", image: "assets/products_shop_images/hex-key-tool-15-mm.png", category: "Accessories", url: "contact-us.html" },
  { name: "USB 2S LiPo Charger", image: "assets/products_shop_images/usb-2s-lipo-charger.png", category: "Accessories", url: "contact-us.html" },
  { name: "Bent Nose Pliers", image: "assets/products_shop_images/bent-nose-pliers.png", category: "Accessories", url: "contact-us.html" },
  { name: "Lighthouse Deck", image: "assets/products_shop_images/lighthouse-deck_2.png", category: "Accessories", url: "contact-us.html" },
  { name: "Lighthouse Head Kit", image: "assets/products_shop_images/lighthouse-head-kit-for-nimble.png", category: "Accessories", url: "contact-us.html" },
  { name: "Lighthouse Shells Kit", image: "assets/products_shop_images/lighthouse-shells-kit-for-nimble_1.png", category: "Accessories", url: "contact-us.html" },
];
